models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h
      entity_key: user
      edge_sources:
        - from: inputs/marketing_site_identifies
        - from: inputs/shopify_orders

  - name: user_profile
    model_type: feature_table_model
    model_spec:
      validity_time: 24h
      entity_key: user
      features:
        - first_name
        - last_name
        - user_lifespan
        - days_active
        - revenue
        - order_count

var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: first_name
          select: FIRST_VALUE(first_name)
          from: inputs/shopify_orders
          where: first_name IS NOT NULL
          window:
            order_by:
              - timestamp DESC
      - entity_var:
          name: last_name
          select: FIRST_VALUE(last_name)
          from: inputs/shopify_orders
          where: last_name IS NOT NULL
          window:
            order_by:
              - timestamp DESC
      - entity_var:
          name: first_seen
          select: MIN(CAST(timestamp AS date))
          from: inputs/marketing_site_pages
          is_feature: false
      - entity_var:
          name: last_seen
          select: MAX(CAST(timestamp AS date))
          from: inputs/marketing_site_pages
          is_feature: false
      - entity_var:
          name: user_lifespan
          select: '{{user.Var("last_seen")}} - {{user.Var("first_seen")}}'
      - entity_var:
          name: days_active
          select: COUNT(DISTINCT CAST(timestamp AS date))
          from: inputs/marketing_site_pages
      - entity_var:
          name: revenue
          select: SUM(order_amount)
          from: inputs/shopify_orders
      - entity_var:
          name: order_count
          select: COUNT(order_number)
          from: inputs/shopify_orders
