models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h
      entity_key: user
      edge_sources:
        - from: inputs/marketing_site_identifies

  - name: user_profile
    model_type: feature_table_model
    model_spec:
      validity_time: 24h
      entity_key: user
      features:
        - user_lifespan
        - days_active

var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: first_seen
          select: MIN(CAST(timestamp AS date))
          from: inputs/marketing_site_pages
          is_feature: false
      - entity_var:
          name: last_seen
          select: MAX(CAST(timestamp AS date))
          from: inputs/marketing_site_pages
          is_feature: false
      - entity_var:
          name: user_lifespan
          select: '{{user.Var("last_seen")}} - {{user.Var("first_seen")}}'
          description: Life Time Value of a customer
      - entity_var:
          name: days_active
          select: COUNT(DISTINCT CAST(timestamp AS date))
          from: inputs/marketing_site_pages
          description: No. of days a customer was active
